public class PMHR_Utilities {
    public static final String HERO_GAME_VERSION_RED = 'Red';

    public static final String NUZLOCKE_END_STATUS_SUCCESS = 'Success';
    public static final String NUZLOCKE_END_STATUS_FAILED = 'Failed';
    public static final String NUZLOCKE_LEGENDARIES_RULE_KILL = 'Kill';

    public static final String POKEMON_CATCH_METHOD_EVENT = 'Event';

    public static final String GENDER_MALE = 'Male';

    public static final String REGION_VARIANT_STANDARD = 'Standard';
    public static final String REGION_VARIANT_ALOLAN = 'Alolan';
    public static final String REGION_VARIANT_GALARIAN = 'Galarian';
}